region        = "${{ values.region }}"
profile       = "${{ values.profile }}"
bucket_name   = "${{ values.bucket_name }}"
dynamodb_name = "${{ values.dynamodb_lock_table_name }}"
project_name = "${{ values.component_id }}"
