profile     = "${{ values.profile }}"
environment = "${{ values.iac_environment }}"
namespace   = "${{ values.iac_namespace }}"
name        = "${{ values.iac_name_suffix }}"
region      = "${{ values.region }}"
